using System;
using Content.Shared.ERP.UI;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wega.ERP.UI;

[GenerateTypedNameReferences]
public sealed partial class ErpPanelWindow : FancyWindow
{
    public event Action<Status>? StatusSelected;

    private bool _updating;

    public ErpPanelWindow()
    {
        RobustXamlLoader.Load(this);

        StatusButton.AddItem(Loc.GetString("humanoid-profile-editor-status-no-text"), (int) Status.No);
        StatusButton.AddItem(Loc.GetString("humanoid-profile-editor-status-semi-text"), (int) Status.Semi);
        StatusButton.AddItem(Loc.GetString("humanoid-profile-editor-status-full-text"), (int) Status.Full);
        StatusButton.AddItem(Loc.GetString("humanoid-profile-editor-status-absolute-text"), (int) Status.Absolute);

        StatusButton.OnItemSelected += args =>
        {
            StatusButton.SelectId(args.Id);

            if (_updating)
                return;

            StatusSelected?.Invoke((Status) args.Id);
        };
    }

    public void UpdateState(ErpPanelEuiState state)
    {
        _updating = true;
        StatusButton.SelectId((int) state.Status);
        _updating = false;
    }
}
